language: php

matrix:
  fast_finish: true
  include:
  - php: 7.2
    env:
    - DEPENDENCIES=""
    - ARANGODB_VERSION=3.3.19
  - php: 7.2
    env:
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - ARANGODB_VERSION=3.4.10
  - php: 7.3
    env:
    - DEPENDENCIES=""
    - EXECUTE_CS_CHECK=true
    - ARANGODB_VERSION=3.5.5
  - php: 7.3
    env:
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - ARANGODB_VERSION=3.5.5
  - php: 7.4
    env:
    - DEPENDENCIES=""
    - TEST_COVERAGE=true
    - ARANGODB_VERSION=3.6.4
  - php: 7.4
    env:
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - ARANGODB_VERSION=latest

addons:
  hosts:
  - arangodb

cache:
  directories:
  - $HOME/.composer/cache
  - $HOME/.php-cs-fixer
  - $HOME/.local

before_script:
- mkdir -p "$HOME/.php-cs-fixer"
- composer self-update
- composer update --prefer-dist $DEPENDENCIES
- ./test/travis/setup_arangodb.sh

script:
- if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run; fi
- if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/docheader check src/ tests/; fi
- if [[ $TEST_COVERAGE == 'true' ]]; then php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml; fi
- if [[ $TEST_COVERAGE != 'true' ]]; then php ./vendor/bin/phpunit; fi

after_success:
- if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/coveralls -v; fi
